services:
  honeybee_core:
    build:
      context: .
      dockerfile: dockerfile
    container_name: honeybee_core
    network_mode: "host"
    volumes:
      - ./configs/core_config.yaml:/app/configs/config.yaml
    restart: unless-stopped