services:
  honeybee_core:
    build:
      context: .
      dockerfile: dockerfile
    container_name: honeybee_core
    network_mode: host
    volumes:
      - ./bee_config.toml:/app/bee_config.toml
    restart: unless-stopped