unstable_features = true

tab_spaces = 2
max_width = 130
chain_width = 50
enum_discrim_align_threshold = 30
struct_field_align_threshold = 30

fn_single_line = true
fn_params_layout = "Compressed"
imports_layout = "Vertical"
fn_call_width = 80
format_code_in_doc_comments = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"
wrap_comments = true
comment_width = 100

reorder_imports = true
reorder_modules = true
