[package]
name = "bee_cli"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
bee_message = { workspace = true }
tokio = { workspace = true }
